frontend:
    build:
      context: ./frontend-react
      args:
        # POINT DIRECTLY TO THE PUBLIC IP AND PORT OF YOUR AUTH SERVICE
        - VITE_AUTH_API_URL=http://100.54.250.41:8080
        - VITE_VENUE_API_URL=http://100.54.250.41:5059
        - VITE_ATTENDEE_API_URL=http://100.54.250.41:5001
    ports:
      - "5173:80"
    depends_on:
      - auth-service
      - venue-service
      - attendee-service