server {
    listen 80;

    # Serve the React Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy Auth Service (Java)
    # This matches /api/auth/ and sends /auth/ to the Java container
    location /api/auth/ {
        proxy_pass http://auth-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy Venue Service (.NET)
    location /api/venue/ {
        proxy_pass http://venue-service:5059;
        proxy_set_header Host $host;
    }

    # Proxy Attendee Service (Node.js)
    location /api/attendee/ {
        proxy_pass http://attendee-service:5001;
        proxy_set_header Host $host;
    }
}