server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Forward Auth requests to Java Service
    location /api/auth/ {
        proxy_pass http://auth-service:8080/auth/;
    }

    # Forward Venue requests to .NET Service
    location /api/venue/ {
        proxy_pass http://venue-service:5059/api/venue/;
    }

    # Forward Booking requests to Node Service
    location /api/booking/ {
        proxy_pass http://attendee-service:5001/api/bookings/;
    }
}