server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        # REMOVE the "/" at the end of 8080. This is the fix!
        proxy_pass http://auth-service:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/venue/ {
        proxy_pass http://venue-service:5059;
        proxy_set_header Host $host;
    }
}